### ISSUE TITLE
sed: 1: "AdminLTE.css": invalid command code A

### ISSUE THREAD

**Issue by feross** [FaCuZ/torrentmedia#1]
I was trying to get this running on macOS 10.12 Sierra and ran into the following issue:

```
$ npm run adminlte

> torrentmedia@0.1.0 adminlte /Users/feross/code/torrentmedia
> echo 'Making offline AdminLTE...' && cd node_modules/admin-lte/dist/css/ && sed -i '1i/*' AdminLTE.css

Making offline AdminLTE...
sed: 1: "AdminLTE.css": invalid command code A

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "adminlte"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
```

Does the `sed` command take different arguments on different platforms?

**Comment by FaCuZ** [comment]
Yes, I know but 'npm run adminlte' its only for remove the online fonts of AdminLTE template, its not really necessary. 
I fix it at the last commit, I think. I can't test it because i don't have a Mac.
