### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HDVinnie** [FaCuZ/torrentmedia#3]
MacBook-Pro:torrentmedia Vinnie$ npm run-script adminlte

> torrentmedia@0.1.0 adminlte /Users/Vinnie/torrentmedia
> echo 'Making offline AdminLTE...' && cd node_modules/admin-lte/dist/css/ && sed -i.bak '1i/*' AdminLTE.css

Making offline AdminLTE...
sh: line 0: cd: node_modules/admin-lte/dist/css/: No such file or directory

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "adminlte"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! torrentmedia@0.1.0 adminlte: `echo 'Making offline AdminLTE...' && cd node_modules/admin-lte/dist/css/ && sed -i.bak '1i/*' AdminLTE.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the torrentmedia@0.1.0 adminlte script 'echo 'Making offline AdminLTE...' && cd node_modules/admin-lte/dist/css/ && sed -i.bak '1i/_' AdminLTE.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the torrentmedia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'Making offline AdminLTE...' && cd node_modules/admin-lte/dist/css/ && sed -i.bak '1i/_' AdminLTE.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs torrentmedia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls torrentmedia
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Vinnie/torrentmedia/npm-debug.log

**Comment by Porco-Rosso** [comment]
try npm start

**Comment by FaCuZ** [comment]
The command `npm run-script adminlte` is not really necessary.
